name: crrsa_mob_app
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  get: ^4.7.2
  mobile_scanner: ^5.2.3
  image_picker: ^1.1.2
  qr_flutter: ^4.1.0
  permission_handler: ^11.3.1
  carousel_slider: ^5.1.1
  shimmer: ^3.0.0
  get_cli: ^1.9.1
  hugeicons: ^0.0.5
  icons_plus: ^5.0.0
  share_plus: ^10.0.2
  http: ^1.2.2
  shared_preferences: ^2.3.3
  dio: ^5.4.4

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^5.0.0


flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/fonts/

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf
        - asset: assets/fonts/Montserrat-Bold.ttf
          weight: 700
        - asset: assets/fonts/Montserrat-Light.ttf
          weight: 300

    - family: InriaSans
      fonts:
        - asset: assets/fonts/InriaSans-Regular.ttf
        - asset: assets/fonts/InriaSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/InriaSans-Light.ttf
          weight: 300
        - asset: assets/fonts/InriaSans-Italic.ttf
          style: italic